import React from "react";
import {
    Lightbulb,
    Users,
    Zap,
    Palette,
    Megaphone,
    Code,
    HeadphonesIcon,
    PenTool,
    Calendar,
    ChevronUp,
    Mail,
    Phone,
    MapPin,
    Facebook,
    Twitter,
    Instagram,
    Linkedin,
    Handshake,
} from "lucide-react";

export const iconMap: { [key: string]: React.ComponentType<any> } = {
    Lightbulb: Lightbulb,
    Users: Users,
    Zap: Zap,
    Palette: Palette,
    Megaphone: Megaphone,
    Code: Code,
    HeadphonesIcon: HeadphonesIcon,
    PenTool: PenTool,
    Calendar: Calendar,
    ChevronUp: ChevronUp,
    Mail: Mail,
    Phone: Phone,
    MapPin: MapPin,
    Facebook: Facebook,
    Twitter: Twitter,
    Instagram: Instagram,
    Linkedin: Linkedin,
    Handshake: Handshake,
};